# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost-quota-monitor" do
  version "0.0.4"

  on_macos do
    on_intel do
      sha256 "f1a546ae5810196771e9b396ebdfb727ce14f9fc65ab7bf1390d3474ee7e595d"
      url "https://github.com/tedwardd/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tedwardd/bifrost-quota-monitor/"
    end
    on_arm do
      sha256 "9b475838dbd3aa69a1d8fee0297933b127db32a38061863e14f74ea2523859b9"
      url "https://github.com/tedwardd/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tedwardd/bifrost-quota-monitor/"
    end
  end

  on_linux do
    on_intel do
      sha256 "203effd4d1f912b411dc6d8a7146fa350e208c34755cbd9326f65ba0b6a8668b"
      url "https://github.com/tedwardd/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tedwardd/bifrost-quota-monitor/"
    end
    on_arm do
      sha256 "2914f880bd32e4c27e56b57b2f46cafb6a19da38ecc6f203b7384ddcfd30f367"
      url "https://github.com/tedwardd/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tedwardd/bifrost-quota-monitor/"
    end
  end

  name "bifrost-quota-monitor"
  desc "tmux status bar segment showing Bifrost virtual key budget usage"
  homepage "https://github.com/tedwardd/bifrost-quota-monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost-quota-monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifrost-quota-monitor"]
      # An upgrade swaps the binary but leaves the running agent on the old
      # one, since nothing here manages launchd. Restart it when init has
      # already installed the agent, and stay quiet when it has not.
      label = "com.github.tedwardd.bifrost-quota-monitor"
      if File.exist?(File.expand_path("~/Library/LaunchAgents/#{label}.plist"))
        system_command "/bin/launchctl",
                       args: ["kickstart", "-k", "gui/#{Process.uid}/#{label}"],
                       must_succeed: false
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Set BIFROST_BASE_URL and BIFROST_API_KEY, then run 'bifrost-quota-monitor init' to install the launchd agent and patch your tmux config. There is no default gateway address, since Bifrost is self-hosted. See https://github.com/tedwardd/bifrost-quota-monitor for setup and troubleshooting.
  EOS
end
