# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost-quota-monitor" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "fb0dce9209bffe0e3b5487880f6fd7c1e01eff0142f151dad205dbd0111c6eb2"
      url "https://github.com/tedwardd/bifrost-usage-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tedwardd/bifrost-usage-monitor/"
    end
    on_arm do
      sha256 "651211e472a21dc6f98226d52415e81eb85063f2f351c6ff73e44fb4baf0f5ab"
      url "https://github.com/tedwardd/bifrost-usage-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tedwardd/bifrost-usage-monitor/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c819954b2a1ba90f916fd7ba12cbfc72c374ce8c78788c5307ace084784c6e45"
      url "https://github.com/tedwardd/bifrost-usage-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tedwardd/bifrost-usage-monitor/"
    end
    on_arm do
      sha256 "6adb10d61d8ce8afdf04acb225a31535836cc42aad070f2039f231fa137bcec3"
      url "https://github.com/tedwardd/bifrost-usage-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tedwardd/bifrost-usage-monitor/"
    end
  end

  name "bifrost-quota-monitor"
  desc "tmux status bar segment showing Bifrost virtual key budget usage"
  homepage "https://github.com/tedwardd/bifrost-usage-monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost-quota-monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifrost-quota-monitor"]
      # An upgrade swaps the binary but leaves the running agent on the old
      # one, since nothing here manages launchd. Restart it when init has
      # already installed the agent, and stay quiet when it has not.
      label = "com.github.tedwardd.bifrost-quota-monitor"
      if File.exist?(File.expand_path("~/Library/LaunchAgents/#{label}.plist"))
        system_command "/bin/launchctl",
                       args: ["kickstart", "-k", "gui/#{Process.uid}/#{label}"],
                       must_succeed: false
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Set BIFROST_BASE_URL and BIFROST_API_KEY, then run 'bifrost-quota-monitor init' to install the launchd agent and patch your tmux config. There is no default gateway address, since Bifrost is self-hosted. See https://github.com/tedwardd/bifrost-usage-monitor for setup and troubleshooting.
  EOS
end
