# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-monitor" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "823ce51b85894c7135d93f8a4b41712fe03e9f3f3a00b955c5e2a849a97c0ea0"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
    on_arm do
      sha256 "82522798d0e6c0b8ae056624bc749b6fbde2a307fa9754685721e9f4c13ad934"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
  end

  on_linux do
    on_intel do
      sha256 "2904ccef9ba921fa2740c1f960b0ea004fa866c11c9028cbba7540caf44db269"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
    on_arm do
      sha256 "3373122bebe4e760c99532314ce9736d4b7e035fb8388b532fd412fb1c76e8a8"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
  end

  name "claude-monitor"
  desc "tmux status bar daemon displaying Claude Pro quota usage in real time"
  homepage "https://github.com/tedwardd/tmux-claude-monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-monitor"]
      # An upgrade swaps the binary but leaves the running agent on the old one,
      # since nothing here manages launchd. Restart it when init has already
      # installed the agent, and stay quiet when it has not.
      label = "com.github.tedwardd.claude-monitor"
      if File.exist?(File.expand_path("~/Library/LaunchAgents/#{label}.plist"))
        system_command "/bin/launchctl",
                       args: ["kickstart", "-k", "gui/#{Process.uid}/#{label}"],
                       must_succeed: false
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run the one-time setup to install the launchd agent and patch your tmux config:

      claude-monitor init

    The daemon reads your Claude Code OAuth token from the login keychain.
    If macOS asks whether security can access it, choose "Always Allow".
  EOS
end
