# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-monitor" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "9d450baf9b4db620f0b6e29e1a62f342cfbd02b484d00a265da71172c783e29b"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
    on_arm do
      sha256 "9871e8e6b1a5625abc8d4aad572c81d472365e0b157f98d47f65f6a31ddd74cf"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
  end

  on_linux do
    on_intel do
      sha256 "5b1e833b0ab10bbfebae1c1d5078d164e4fcc0270e9c98a19964ed9330ba353a"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
    on_arm do
      sha256 "058e7fb88576bcb0f0191c8f0d7501fa1cd18f4c774eefac40c3313669c0915c"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
  end

  name "claude-monitor"
  desc "tmux status bar daemon displaying Claude Pro quota usage in real time"
  homepage "https://github.com/tedwardd/tmux-claude-monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-monitor"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run the one-time setup to install the launchd agent and patch your tmux config:

      claude-monitor init

    The daemon reads your Claude Code OAuth token from the login keychain.
    If macOS asks whether security can access it, choose "Always Allow".
  EOS
end
