# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-monitor" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "f7fa7d5100c2e5d68386af4255ae0172a38681c9c0ba2582fae72acded78ce6e"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
    on_arm do
      sha256 "37011a7ac5cbf7d8f73a25da2507174938588ddd5f142eae587bb33086595ed5"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
  end

  on_linux do
    on_intel do
      sha256 "6a478b503f96bf44f833658c40c58784f753bb870e4288eb9d47a66bd6c06450"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_linux_amd64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
    on_arm do
      sha256 "a4705a4e9c88a825b9296c572838c006bf3912c813ce933bcf31dc5066549a25"
      url "https://github.com/tedwardd/tmux-claude-monitor/releases/download/v#{version}/claude-monitor_#{version}_linux_arm64.tar.gz",
        verified: "github.com/tedwardd/tmux-claude-monitor/"
    end
  end

  name "claude-monitor"
  desc "tmux status bar daemon displaying Claude Pro quota usage in real time"
  homepage "https://github.com/tedwardd/tmux-claude-monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-monitor"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run the one-time setup to install the launchd agent and patch your tmux config:

      claude-monitor init

    The daemon reads your Claude Code OAuth token from the login keychain.
    If macOS asks whether security can access it, choose "Always Allow".
  EOS
end
